version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

sphinx:
  builder: html
  configuration: docs/src/conf.py
  fail_on_warning: true

formats: all

python:
  install:
    - sphinx
    - sphinx-rtd-theme
